### PR TITLE
Upgrade `rustfix` to version 0.8

### PR DESCRIPTION
**Pull request by smoelius**
Would it be possible to publish a new release following this upgrade?

Thank you.

### CODE REVIEW

**Comment by smoelius** [comment]
I think I need some guidance here.

Without bfe5c24, the `dyn-keyword` passes with stable but not with nightly.

With bfe5c24, the `dyn-keyword` passes with nightly but not with stable.

How would you prefer to handle the `dyn-keyword` test?

**Comment by Manishearth** [comment]
yeah the CI here isn't in a good state and I don't have the time to fix it.

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
Published 0.11.0

**Comment by smoelius1** [comment]
Thank you very much, @Manishearth.

**Pull request merged**
