### PR TITLE
Update `rustfix` dependency

### PR DESCRIPTION
**Pull request by Munksgaard**
Continued from #252

### CODE REVIEW

**Comment by Munksgaard** [comment]
@smoelius I messed something up in your PR, but I've committed your change here instead.

**Comment by Munksgaard** [comment]
@smoelius rustfix is still failing on nightly, is that on purpose?

**Comment by Munksgaard** [comment]
Oh wait, this is actually compiletest that is failing. Some changes in the internal test library I think

**Comment by smoelius** [comment]
Thank you very much, @Munksgaard!

**Pull request merged**
