### PR TITLE
github: add dependabot config

### PR DESCRIPTION
**Pull request by tamird**

### CODE REVIEW

**Comment by Manishearth** [comment]
I'm not sure I want this because I'm not sure I'm going to pay attention to them, dependabot is more noise than signal for me in most cases.

**Comment by tamird** [comment]
Generally just requires a "@dependabot merge" every once in a while, and saves users from being warned about out of date crates. Does that seem onerous?

**Comment by Manishearth** [comment]
In general I'm doing the minimal necessary to keep this working, especially since clippy is moving to uitest eventually.

It's just more notifications to deal with.

**Comment by Manishearth** [comment]
I guess I'm fine with a weekly PR but if it's many I might turn it off

**Comment by Manishearth** [comment]
Yeah never mind one of the PRs it opened is one I do not wish to spend time evaluating. Gonna revert this.

**Comment by Manishearth** [comment]
Or, well, still might keep it for a bit. We'll see.

In general I do not trust bot dependency updates and feel the need to have at least one human claim it's an ok upgrade

**Pull request merged**
